kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wangyijie-ns-admin
  namespace: wangyijie
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: wangyijie-ns-admin
subjects:
- kind: User
  name: wangyijie
  apiGroup: rbac.authorization.k8s.io